/**
 * `GET /api/audit/runs/{run_id}/export`
 *
 * Port of `backend/app/routers/audit.py#export_run_pdf`: streams the A4 report
 * generated by `lib/server/audit/pdf.ts` with the same
 * `auditify_report_<id[0:8]>.pdf` attachment filename.
 */
import { NextResponse } from "next/server";

import { buildAuditPdf } from "@/lib/server/audit/pdf";
import { getRunDetail } from "@/lib/server/audit/runs";
import { getCurrentUser } from "@/lib/server/auth";
import { ensureSchema } from "@/lib/server/db";
import { HttpError, handleRoute } from "@/lib/server/http";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface RouteContext {
  params: { runId: string };
}

export async function GET(request: Request, context: RouteContext): Promise<NextResponse> {
  return handleRoute(async () => {
    const user = await getCurrentUser(request);
    await ensureSchema();

    const run = await getRunDetail(user.id, context.params.runId);
    if (!run) {
      throw new HttpError(404, "Audit run not found.");
    }

    const pdf = await buildAuditPdf(
      {
        id: run.id,
        spec_filename: run.spec_filename,
        log_filename: run.log_filename,
        model_used: run.model_used,
        compliance_score: run.compliance_score,
        total_checks: run.total_checks,
        passed_checks: run.passed_checks,
        failed_checks: run.failed_checks,
        warning_checks: run.warning_checks,
        critical_violations: run.critical_violations,
        created_at: run.created_at,
      },
      run.checks.map((check) => ({
        name: check.name,
        category: check.category,
        status: check.status,
        severity: check.severity,
        source: check.source,
        description: check.description,
        recommendation: check.recommendation,
      }))
    );

    return new NextResponse(Buffer.from(pdf), {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="auditify_report_${run.id.slice(0, 8)}.pdf"`,
      },
    });
  });
}
